// Disable access to DOM typings and instantiate service worker globals
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

// Ensure proper type definitions
/// <reference types="@sveltejs/kit" />

import { build, files, version } from '$service-worker';

// Give `self` the correct types
const self: ServiceWorkerGlobalScope = globalThis as unknown as ServiceWorkerGlobalScope;

// Create a unique cache name for this deployment
const CACHE = `cache-${version}`;

// All assets to cache: build files + static files
const ASSETS = [
	...build, // App itself (JS, CSS generated by Vite)
	...files // Everything in `static/` (images, icons, etc.)
];

// Installation du Service Worker
self.addEventListener('install', (event) => {
	console.log('📦 Service Worker installé');

	// Create a new cache and add all files to it
	async function addFilesToCache() {
		const cache = await caches.open(CACHE);
		await cache.addAll(ASSETS);
	}

	event.waitUntil(addFilesToCache());
});

// Activation du Service Worker
self.addEventListener('activate', (event) => {
	console.log('✅ Service Worker activé');

	// Remove previous cached data from disk
	async function deleteOldCaches() {
		for (const key of await caches.keys()) {
			if (key !== CACHE) await caches.delete(key);
		}
	}

	event.waitUntil(deleteOldCaches());
});

// Intercepter les requêtes réseau (Cache First strategy)
self.addEventListener('fetch', (event) => {
	// Ignore POST requests etc
	if (event.request.method !== 'GET') return;

	async function respond() {
		const url = new URL(event.request.url);
		const cache = await caches.open(CACHE);

		// `build`/`files` can always be served from the cache
		if (ASSETS.includes(url.pathname)) {
			const response = await cache.match(url.pathname);
			if (response) {
				return response;
			}
		}

		// For everything else, try network first, fall back to cache if offline
		try {
			const response = await fetch(event.request);

			// If offline, fetch can return a non-Response value
			if (!(response instanceof Response)) {
				throw new Error('invalid response from fetch');
			}

			// Cache successful responses for future use
			if (response.status === 200) {
				cache.put(event.request, response.clone());
			}

			return response;
		} catch (err) {
			// Offline: try cache
			const response = await cache.match(event.request);
			if (response) {
				return response;
			}

			// Nothing we can do - no cache and offline
			throw err;
		}
	}

	event.respondWith(respond());
});

// Gestion des notifications push
self.addEventListener('push', (event) => {
	const data = event.data?.json() ?? {};
	console.log('📬 Notification push reçue:', data);

	event.waitUntil(
		self.registration.showNotification(data.title ?? 'Oupla Planning', {
			body: data.body,
			icon: '/icon-192.png',
			badge: '/badge-72.png',
			data: { url: data.url ?? '/' },
			requireInteraction: false
		})
	);
});

// Clic sur une notification → ouvre l'URL correspondante
self.addEventListener('notificationclick', (event) => {
	event.notification.close();

	const urlToOpen = event.notification.data?.url ?? '/';

	event.waitUntil(
		self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
			// Réutiliser un onglet existant si possible
			for (const client of clientList) {
				if ('navigate' in client && client.url === urlToOpen) {
					(client as WindowClient).focus();
					return;
				}
				if ('navigate' in client) {
					(client as WindowClient).focus();
					(client as WindowClient).navigate(urlToOpen);
					return;
				}
			}
			// Sinon ouvrir une nouvelle fenêtre
			return self.clients.openWindow(urlToOpen);
		})
	);
});
